config/routes.rb
Topdevjob::Application.routes.draw do
  resources :jobs

  devise_for :users

  get '/', to: 'jobs#index', constraints: { subdomain: 'jobs'}
   resources  :job_steps do
     collection do
       post  :preview
       patch :preview
       post :register
       get  :register
       get  :confirm
       get  :fine
     end
   end
   get 'perche-annunci-per-sviluppatori-italia', to: "jobs#perche", as: :perche
   root to: 'jobs#index'
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :titolo, :descrizione, :nome_azienda, :user_id, presence: true
  validates :email,  format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :sito_web, format: { without: /http/, message: 'non necessita di http'}
  belongs_to :user

  def self.search(params)
    scope = scoped.order("created_at Desc").select('id, titolo, nome_azienda, created_at')
    scope = scope.where(["titolo LIKE ? OR descrizione LIKE ? OR nome_azienda LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%","%#{params[:q]}%" ]) if params[:q].present?
    scope
  end

  def to_param
    "#{self.id}-#{nome_azienda}-#{titolo}".parameterize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable, :registerable, :recoverable

  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'jobs'
  def after_sign_in_path_for(resource)
    cookies[:job].present? ? fine_job_steps_path : root_path
  end

  protected

    def admin!
      if current_user
       redirect_to root_path unless current_user.admin == 1
     else
       redirect_to root_path
      end
    end
end

app/controllers/job_steps_controller.rb
class JobStepsController < ApplicationController
  before_filter :authenticate_user!, only: :fine

  def new
    @job = Job.new
  end

  def edit
    @job = if job.present?
      Job.new job
    else
      current_user.jobs.find(params[:id])
    end
  end

  def preview
    @job = Job.new job_params
    @job.user_id = SecureRandom.random_number(100)
    if @job.valid?
      add_job_cookie
    else
      render 'new'
    end
  end

  def fine
    @job = current_user.jobs.build job
    if @job.save
      flash[:notice] = "operazione eseguita con successo"
      delete_job
    else
      redirect_to new_job_step_path
    end
  end

  private

    def job_params
      params.require(:job).permit(:titolo, :sito_web, :email, :descrizione, :nome_azienda)
    end

    def delete_job
      cookies.delete(:job)
    end

    def add_job_cookie
      cookies[:job] = @job.to_json
    end

    def job
      JSON.parse(cookies[:job] || "{}")
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:create, :edit, :update, :destroy]

  def index
    @jobs = jobs
  end

  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to fine_job_steps_path, notice: 'Annuncio aggiunto con successo.'
    else
      render 'new'
    end
  end

  def update
    if @job.update(job_params)
      redirect_to fine_job_steps_path, notice: 'Annuncio modificato con successo.'
    else
      render  'edit'
    end
  end

  def destroy
    @job = current_user.jobs.find(params[:id])
    if @job.destroy
      redirect_to jobs_url(my_jobs: :true), notice: 'Annuncio cancellato con successo.'
    else
      redirect_to jobs_url(my_jobs: :true), notice: 'Annuncio non cancellato.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def job_params
      params.require(:job).permit(:titolo, :sito_web, :email, :descrizione, :nome_azienda)
    end

    def jobs

      if params[:my_jobs] == "true"
        current_user.jobs.search(params)
      else
        Job.search(params)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def mark_down(string)
    BlueCloth.new(string).to_html.html_safe
  end

  def steps(arg)
    if arg.is_a? Array
      "badge-success" if arg.include? request.path
    else
      "badge-success" if arg == request.path
    end
  end

  def is_mine?(job)
    current_user && current_user.id == job.user_id
  end
end

app/views/job_steps/_form.erb
<%= form_for(@job , url: preview_job_steps_path, html: {class: 'form-horizontal'}) do |f| %>

  <div class="control-group">
    <%= f.label :titolo, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :titolo %>
    </div>
  </div>

   <div class="control-group">
     <%= f.label :nome_azienda,  class: 'control-label'%>
     <div class="controls">
       <%= f.text_field :nome_azienda %>
     </div>
   </div>
  <div class="control-group">
    <%= f.label "Sito Web http://",  class: 'control-label'%>
    <div class="controls">
      <%= f.text_field :sito_web %>
    </div>
  </div>
  <div class="control-group">
      <%= label_tag "desc",raw('Descrizione <br/> <a href="http://daringfireball.net/projects/markdown/">puoi usare il markdown</a>'), class: 'control-label' %> <br />
      <div class="controls">
        <%= f.text_area :descrizione, cols: '100' %>
      </div>
    </div>
  <div class="control-group">
    <%= f.label :email, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :email %>
     </div>
  </div>
  <div class="actions">
    <div class="controls">
      <%= f.submit 'Continua', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/job_steps/_wizard.erb
<ul id="steps" class="breadcrumb <%= "#{controller_name}_#{action_name}"%> ">
  <li>
    <span id="aggiungi" class="badge">1</span>
    <span><%= action_name == 'new' ? "Aggiungi" : "Modifica" %> </span>
    <span class="divider">|</span>
  </li>
  <li>
    <span id="preview" class="badge">2</span>
    <span>Preview</span>
    <span class="divider">|</span>
  </li>
  <li>
    <span id="registrati" class="badge">3</span>
    <span>Registrati</span>
    <span class="divider">|</span>
  </li>
  <li>
     <span id="fine" class="badge">4</span>
     <span>Fine</span>
   </li>
</ul>

app/views/job_steps/edit.html.erb
<%= render 'wizard' %>

<%= render 'form' %>

app/views/job_steps/fine.html.erb
<%= render 'wizard' %>

<div id="fine">
  <h1>Complimenti!</h1>
  <p><%= flash[:notice] %></p>
  <p>
    <%= link_to "Vai alla lista Annunci", root_path, class: "btn btn-primary btn-large btn-success" %>
  </p>
</div>

app/views/job_steps/new.html.erb
<%= render 'wizard' %>

<%= render 'form' %>

app/views/job_steps/preview.html.erb
<%= render 'wizard' %>
<%= render 'jobs/show'%>
<% unless @job.new_record? %>
  <%= link_to 'Back', jobs_path %>
<% else %>
  <% if current_user %>
    <%= link_to 'Continua', fine_job_steps_path, class: 'btn btn-primary' %>
  <% else %>
    <%= link_to 'Continua', new_user_registration_path, class: 'btn btn-primary' %>
  <% end %>
  o <%= link_to 'Modifica', edit_job_step_path(@job) %>

  <% unless @job.new_record? %>
   | <%= link_to 'Cancella', @job, method: :delete, confirm: 'vuoi cancellare questo annuncio?' %>
  <% end %>

<% end %>

app/views/jobs/_form.html.erb
<%= form_for(@job, html: {class: 'form-horizontal'}) do |f| %>

  <div class="control-group">
    <%= f.label :titolo, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :titolo %>
    </div>
  </div>

   <div class="control-group">
     <%= f.label :nome_azienda,  class: 'control-label'%>
     <div class="controls">
       <%= f.text_field :nome_azienda %>
     </div>
   </div>
  <div class="control-group">
    <%= f.label "Sito Web http://",  class: 'control-label'%>
    <div class="controls">
      <%= f.text_field :sito_web %>
    </div>
  </div>
  <div class="control-group">
      <%= label_tag "desc",raw('Descrizione <br/> <a href="http://daringfireball.net/projects/markdown/">puoi usare il markdown</a>'), class: 'control-label' %> <br />
      <div class="controls">
        <%= f.text_area :descrizione, cols: '100' %>
      </div>
    </div>
  <div class="field">
    <%= f.label :email, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :email %>
     </div>
  </div>
  <div class="actions">
    <div class="controls">
      <%= f.submit 'Aggiungi', class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/jobs/_job.erb
<li class="job  span12">
 <b class="nome"> <%= job.nome_azienda %> </b>
  <%= link_to job do %>
  <span class="titolo"><%= job.titolo %></span>
  <span class="data"> <%= l job.created_at.to_date, format: :short %> </span>
  <% end %>
</li>

app/views/jobs/_search.erb
<% if action_name == 'index'  %>
 <div class="well row">
  <div class="span8">
  <%= form_tag :jobs, url: root_path, method: :get, class: 'form-search' do %>
    <%= text_field_tag :q,'',class: ' search-query', placeholder: 'Search: ruby, redis, rails, php ...' %>
    <%= submit_tag 'Cerca', class: 'btn-large btn-success'%>
  <% end %>
   </div>

    <div  id="new_job_link" class="span3">
      <%=# link_to "Fai un annuncio Gratis", new_job_path, class: 'btn-large btn-danger'
       %>
      <%= link_to "Fai un annuncio Gratis", new_job_step_path, class: 'btn-large btn-danger' %>
    </div>
  </div>

<% end %>

app/views/jobs/_show.erb
<p id="notice"><%= notice %></p>


<h1 id="titolo"> <%= @job.titolo %> </h1>

<div id="data" > <%= l (@job.created_at || DateTime.now).to_date, format: :short %> </div>

<section id="azienda">
 <h3 id="nome_azienda">  <%= @job.nome_azienda %> </h3>
 <h3 id="nome_azienda">  <%= link_to "http://#{@job.sito_web}", "http://#{@job.sito_web}"  %> </h3>
</section>


<section id="description">
<p>
 <%= mark_down @job.descrizione %>
</p>
</section>

<p>
<%= @job.email %>
</p>

app/views/jobs/edit.html.erb
<h1>Modifica Annuncio</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<div class="row">
  <div class="span12">
    <div class="content">
      <section class="span12">
        <article>
          <h2> Ultimi Annunci </h2>
          <ul id="jobs">
           <%= render @jobs %>
          </ul>
        </article>
      </section>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<%= link_to '&#8592; Back'.html_safe , jobs_path %>

<h1>Crea  annuncio </h1>

<%= render 'form' %>

app/views/jobs/show.html.erb
<% if @job.new_record? %>
  <%= link_to '&#8592; Back'.html_safe , new_job_step_path, class: :back %>
<% else %>
  <%= link_to '&#8592; Back'.html_safe , jobs_path, class: :back  %>
<% end %>

<%= render 'jobs/show'%>
<% if is_mine?(@job) %>
  <%= link_to 'Modifica', edit_job_step_path(@job) %>
| <%= link_to 'Cancella', @job, method: :delete, confirm: 'vuoi cancellare questo annuncio?' unless @job.new_record? %>
<% end %>

app/views/layouts/_analitycs.erb
<% if Rails.env.production? %>
<!-- google analytics here -->
<% end %>

app/views/layouts/_footer.erb
<li><%= link_to 'Home', root_path %></li>
<li class="muted">·</li>
<li><%= link_to 'Perchè questa bacheca', perche_path %></li>
<li class="muted">·</li>
<li><%= link_to 'Account', jobs_path(my_jobs: true) %></li>
<li class="muted">·</li>
<li><%= link_to 'rss', root_path(format: :rss) %></li>
<li class="muted">·</li>
<li><%= mail_to "topdevelopers.it@gmail.com", 'email' %></li>

app/views/layouts/_header.erb
 <div id="spot">
    <h1><%= link_to 'Annunci', root_path %></h1>
    <p class="lead">di lavoro per sviluppatori e hacker in Italia.</p>
  </div>
  <div id="sharing">
   <%= link_to root_path(format: :rss) do %>
     <%= image_tag 'rss.png', alt: 'rss lavoro per sviluppatori e hacker itaiani', style: 'float: right'%>
   <% end %>
    <ul>
      <li> <%=link_to '', "http://www.twitter.com/share?url=http://jobs.topdevelopers.it&text=Annunci Lavoro Sviluppatori e Developers in Italia", class:"icons-twitter", "data-original-title"=> "condividi su twitter" %></a></li>
      <li> <%=link_to '', "http://www.facebook.com/share.php?u=http://jobs.topdevelopers.it", class:"icons-facebook", "data-original-title"=> "condividi su facebook" %></li>
      <li> <%=link_to '', "http://www.linkedin.com/shareArticle?mini=true&url=http://jobs.topdevelopers.it", class:"icons-linkedin", "data-original-title"=> "condividi su linkedin" %></li>
      <li> <%=link_to '', "https://plus.google.com/share?url=http://jobs.topdevelopers.it", class:"icons-googleplus","data-original-title"=> "condividi su googleplus" %></li>
    </ul>
  </div>

app/views/layouts/jobs.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Annunci Lavoro Sviluppatori e Developers in Italia</title>
  <meta name="description" content="Newletter Hacking Scaling e Startup in Italia"/>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body id="job">
  <header id="overview" class="hero-unit <%= action_name %>">
    <div class="container">
     <%= render 'layouts/header'%>
    </div>
  </header>

  <div class="container">
    <div id="search">
      <%= render 'jobs/search' %>
    </div>
    <%= yield %>
  </div>

  <div id="footer">
    <div class="container">
      <ul class="footer-links">
        <%= render 'layouts/footer'%>
      </ul>
    </div>
  </div>
  <%= render 'layouts/analitycs'%>
</body>
</html>